export const header =[
    {   
        id:'id',
        header:'S.No'
    },
    {   
        name:'name',
        header:'Name'
    },
    {   
        age:'age',
        header:'Age'
    },
    {   
        country:'country',
        header:'Country'
    },
    {   
        position:'position',
        header:'Position'
    },
    {   
        wage:'wage',
        header:'Wage'
    },{
        action:'action',
        header:'Action'
    }    
] 